### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TobaT3** [ivanhrabcak/edupage-api#71]
**Describe the bug**
When requesting grades, if the grade is not one of the three types in the code (eg. is not 1-5, points or  percentages but for example text), max_points and possibly something else will be undefined.

**Your code**
```python
allgrades = edupage.get_grades()
```

**Error message**
```
Traceback (most recent call last):
  File "/home/toba/Code/edupage-api-test/main.py", line 28, in <module>
    getGrades()
  File "/home/toba/Code/edupage-api-test/main.py", line 23, in getGrades
    allgrades = edupage.get_grades()
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/toba/.local/lib/python3.11/site-packages/edupage_api/__init__.py", line 158, in get_grades
    return Grades(self).get_grades(year=None, term=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toba/.local/lib/python3.11/site-packages/edupage_api/module.py", line 95, in __impl
    return method(self, *method_args, **method_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toba/.local/lib/python3.11/site-packages/edupage_api/grades.py", line 148, in get_grades
    subject_name, teacher, max_points, importance, verbal, percent)
                           ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'max_points' where it is not associated with a value
```

**Expected behavior**

**Version**
- Edupage API version: **0.10.5**
- Python version: **3.11.5**

**Comment by ivanhrabcak** [comment]
Could you try to put a breakpoint in the code and see what `grade_type` is the grade that is erroring out?

If you need help, I suggest we meetup in a call in [my server](https://discord.gg/fg6zBu9ZAn).

**Comment by mgrfilipmarek** [comment]
In our edupage, I can see text grades (pochvaly) only in behavior subject currently.
![Image](https://github.com/user-attachments/assets/b8f4d8ae-ccf1-43ca-89f2-e51c26bb949e)

If I debug edupage api, its in `vsetkyVcelicky` inside `grade_data` @ivanhrabcak can you take a look pls?
![Image](https://github.com/user-attachments/assets/537ad483-5614-4220-b416-6487f68d8166)
